## Two Sample T test

## When to use it? 

##To determine if means are equal

## H1: What you are trying to prove
## H0: The opposite of what you are trying to prove

When formulating your hypothesis, you first come up with the H1 or alternate hypothesis and then your null hypothesis.

In this case the hypothesis is:

H0:There is no difference in the average reading time 
H1:Is there a difference in the average reading time?

In [ ]:
import pandas as pd

# session_times.csv
url = 'https://drive.google.com/file/d/1nYRMCgv3OKaiIUDBPgq-EnE2sWhgrJI3/view?usp=sharing' 
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
session_times = pd.read_csv(path)

session_times.head()

     Page   Time
0  Page A   21.0
1  Page B  253.0
2  Page A   35.0
3  Page B   71.0
4  Page A   67.0

In [ ]:
time_by_session = session_times.groupby("Page")["Time"].mean()
time_by_session

Page
Page A    126.333333
Page B    162.000000
Name: Time, dtype: float64

In [ ]:
page_A = session_times.loc[session_times.Page=="Page A", "Time"]
page_B = session_times.loc[session_times.Page=="Page B", "Time"]

In [ ]:
page_A

0      21.0
2      35.0
4      67.0
6     211.0
8     132.0
10     68.0
12    321.0
14    147.0
16     95.0
18     45.0
20    118.0
22    342.0
24    197.0
26     39.0
28     65.0
30    173.0
31     74.0
32     86.0
33    118.0
34    206.0
35     93.0
Name: Time, dtype: float64

In [ ]:
import scipy.stats as stats

In [ ]:
t_statistic, p_value = stats.ttest_ind(page_A, 
                                       page_B)
#print("p-value:", p_value)

In [ ]:
p_value

0.2690102436392606

In [ ]:
t_statistic, p_value = stats.ttest_ind(page_A, page_B)

In [ ]:
t_statistic

-1.1237042154424814

Use Alpha=0.1

Do you accept or reject the null hypothesis?

## Manual calculation:

Note: We use a different set of data, but the approach here shows you how scipy calculates the t_statistic and the pvalue.

In [ ]:
from math import sqrt
import numpy as np
from numpy.random import seed
from numpy.random import randn
from numpy import mean
from scipy.stats import sem
from scipy.stats import t
from scipy import stats
from scipy.stats import shapiro
import matplotlib

In [ ]:
# seed the random number generator
seed(1)
# generate two independent samples
data1 = randn(100)
data2 = randn(100)

In [ ]:
# function for calculating the t-test for two samples
def independent_ttest(data1, data2):
	# calculate means
	mean1, mean2 = mean(data1), mean(data2)
	# calculate standard errors
	se1, se2 = sem(data1), sem(data2)
	# standard error on the difference between the samples
	sed = sqrt(se1**2.0 + se2**2.0)
	# calculate the t statistic
	t_stat = (mean1 - mean2) / sed
	# degrees of freedom
	df = len(data1) + len(data2) - 2
	# calculate the p-value
	pvalue = (1.0 - t.cdf(abs(t_stat), df)) * 2.0
	# return everything
	return t_stat, pvalue

In [ ]:
# calculate the t test
alpha = 0.05
t_stat, pvalue = independent_ttest(data1, data2)
print('t=%.3f, pvalue=%.3f' % (t_stat,pvalue))

# interpret via p-value
if pvalue > alpha:
	print('Reject null hypothesis that the means are equal.')
else:
	print('Fail to Reject the null hypothesis that the means are equal.')

t=-0.714, pvalue=0.476
Reject null hypothesis that the means are equal.